cache: bundler

language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.5

sudo: false

bundler_args: --retry=3 --jobs=3

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

matrix:
  fast_finish: true

addons:
  code_climate:
    repo_token: 9cf6f118c86a18e38eb6ebac0b832c59899d46f61db8d4b3826de42570c48f90
